version: "3.9"

services:
  database:
    image: postgres:13.3
    restart: always
    container_name: "database"
    environment:
      POSTGRES_DB: "rate"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qwe123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
  api:
    build: .
    depends_on:
      - database
    links:
      - database
volumes:
  postgresql: { }