package main

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
)

type AutoGenerated struct {
	Date  string `json:"date"`
	Base  string `json:"base"`
	Rates struct {
		Jpy string `json:"JPY"`
		Eur string `json:"EUR"`
		Rub string `json:"RUB"`
	} `json:"rates"`
}

func main() {
	resp, err := http.Get("https://api.currencyfreaks.com/v2.0/rates/latest?apikey=92a244e2dcad458e94fe84ad6a2858f2&symbols=RUB,EUR,JPY")
	if err != nil {
		log.Fatalln(err)
	}

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}
	var rate AutoGenerated
	err = json.Unmarshal(body, &rate)
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(rate.Rates)

	exitc := make(chan os.Signal, 1)
	signal.Notify(exitc, os.Interrupt, os.Kill, syscall.SIGTERM)
	<-exitc
}
